samples: Change titles
XboxDev/nxdk pull request #422
Opened 2021-01-14 12:43 UTC by kosmas12

On a side note, as I mentioned in the related issue, XBE_TITLE requires just quotation marks to use spaces and special characters, but GEN_XISO requires quotation marks *and* the \ escape character, thus I wasn't able to make GEN_XISO use the XBE_TITLE. Theoretically, it should have been possible to use \ in XBE_TITLE, but, when used, a simple hex view of the xbe shows that \ is also written to the XBE's title, and doesn't actually escape anything.

If anyone has a way to fix this or a better way to do the naming, I'll gladly accept it.

Closes #372.

2021-01-14 17:15 UTC, Apfel commented
Are you really sure on using colons in file names? Windows' Explorer cries if I try that myself.

2021-01-14 17:33 UTC, kosmas12 commented
@Apfel This has been fixed now by using dashes instead.

Should have no problem on any platform.

2021-01-14 18:17 UTC, Apfel commented
There's no need to escape a dash; it even breaks on Windows.

2021-01-14 18:41 UTC, kosmas12 commented
It should work now.

Checks have passed.

2021-01-26 19:43 UTC, thrimbor requested changes
The review comments above apply to all the changed Makefiles ofc.

The title changes are fine, but with your quotation mark workaround you missed the actual core issue, the xiso rule in the Makefile:

https://github.com/XboxDev/nxdk/blob/535e1c25d6f4ae033e5820e15d595789d45d5897/Makefile#L126

This needs to be changed to `$(VE) $(EXTRACT_XISO) -c $(OUTPUT_DIR) $(XISO_FLAGS) "$@" $(QUIET)` (note the quotation marks).

That way, the name will be properly quoted when passing the parameter, without the quotes ending up in the variable itself.

2021-01-26 19:43 UTC, thrimbor commented on samples/gamma-fade/Makefile
> +XBE_TITLE = "nxdk sample - gamma-fade"
While the quotes are necessary when passing the parameter through the shell to extract-xiso, this is not a good place to add them. People might want to use the `XBE_TITLE` variable for additional stuff, and not realize that the quotation marks are actually part of the string here (they're not in shell scripts, but they are in Makefiles).

Use escaping instead: `nxdk\ sample\ -\ gamma-fade`.

2021-01-26 19:43 UTC, thrimbor commented on samples/gamma-fade/Makefile
> +GEN_XISO = "nxdk\ sample\ -\ gamma-fade.iso"
This is redundant, and should be `GEN_XISO = $(XBE_TITLE).iso` instead.

2021-03-04 09:18 UTC, kosmas12 commented
I added `"$@"` in the nxdk Makefile for XISO gen and added escaping in all the XBE titles

2021-03-05 13:44 UTC, thrimbor commented
I've taken the liberty to slightly improve your commit title and fix the merge conflict. Merging now.

2021-03-05 13:44 UTC, merged