video: Free framebufer of previous running app
XboxDev/nxdk pull request #424
Opened 2021-01-18 13:22 UTC by kosmas12

This has been tested to cause no problems on xemu and a 1.1 Xbox. The project I used to test with is [https://github.com/Ryzee119/SDLPoPX](url).

Closes #357

2021-01-19 17:01 UTC, thrimbor requested changes
The indentation is different in comparison to the surrounding code (tabs vs. spaces).

I don't think `XVideoSetMode` is the best place for this - imho it makes more sense to put it into `XVideoInit`, so the framebuffer doesn't get freed when failing to set a new mode. There, we could also compare the size of the old framebuffer to the framebuffer size of the requested mode, and reuse the old framebuffer instead of allocating a new one.

To fully resolve the linked issue, we should also mark newly allocated framebuffers as persistent, and store their address with `AvSetSavedDataAddress`, so other applications can reuse our framebuffer.

2021-01-19 21:42 UTC, kosmas12 commented
I applied all the suggested improvements and tested them on both xemu and a 1.1 Xbox with [https://github.com/dracc/NevolutionX](url) and [https://github.com/Ryzee119/SDLPoPX](url), all seems to work fine.

2021-02-16 17:05 UTC, thrimbor approved these changes

2021-02-16 17:07 UTC, thrimbor commented
I took the liberty of fixing some smaller remaining issues myself (whitespaces, formatting, commit title too long), merging now.

2021-02-16 17:07 UTC, merged

2021-02-18 04:19 UTC, GXTX commented on lib/hal/video.c
> +	if (previousFB != 0) {
Shouldn't this be `NULL`?

2021-02-18 04:22 UTC, GXTX commented on lib/hal/video.c
> +			memset(previousFB, 0x00, screenSize);
Shouldn't this use `RtlZeroMemory` / `ZeroMemory()`?

2021-02-18 04:26 UTC, GXTX commented on lib/hal/video.c
> +			AvSetSavedDataAddress(NULL);
Is this required? We set a new address once we're out of the if/else block.