vcrt: Fix sign related compilation warnings
XboxDev/nxdk pull request #520
Opened 2021-11-07 19:04 UTC by dracc

Small change silencing a few compilation warnings related to signed/unsigned comparisons.

2021-11-07 20:35 UTC, GXTX commented
We seem to use cpp style casts elsewhere in this file, is there any reason to not use them here?

2021-11-07 20:36 UTC, dracc commented
> We seem to use cpp style casts elsewhere in this file, is there any reason to not use them here?

Lack of attention. I'll correct that. Thanks!

2021-11-08 04:07 UTC, thrimbor requested changes

2021-11-11 06:35 UTC, thrimbor approved these changes
Changes look good. The only modification I'd like to see is the commit title prefix - we have used `vcruntime` instead of `vcrt` in the past.

2021-11-18 03:50 UTC, merged